name: Job-precedence
on:
  workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 2
        run: echo "This is job 2, which depends on job 1"

  job3: 
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Job 3
        run: echo "This is job 3, which also depends on job 1"
  
  job4:
    runs-on: ubuntu-latest
    needs: [job2, job3]
    steps:
      - name: Job 4
        run: echo "This is job 4, which depends on both job 2 and job 3"