name: 2.1 Manual approver
on:
  workflow_dispatch

jobs:
  job-dev:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🎉 The job was triggered by actor: ${{ github.actor }}"
      

  job-preprod:
    runs-on: ubuntu-latest
    needs: job-dev
    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: marcelloraffaele
          minimum-approvals: 1
          issue-title: "Manual Approval Required for preprod"
          issue-body: "Please approve or deny the deployment."
      - name: step 1
        run: echo "This is job-preprod, which depends on job-dev"
      
  
  job-prod:
    runs-on: ubuntu-latest
    needs: [job-preprod]
    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: marcelloraffaele
          minimum-approvals: 1
          issue-title: "Manual Approval Required for prod"
          issue-body: "Please approve or deny the deployment."
      - name: step 1
        run: echo "This is job-prod, which depends on job-preprod"
