# This workflow demonstrates how to use the `workflow_run` event to trigger a job approval process.
# It consists of three jobs: `job-dev`, `job-preprod`, and `job-prod`.
name: 2.Job-approval
on:
  workflow_dispatch

jobs:
  job-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: step 1
        run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🎉 The job was triggered by actor: ${{ github.actor }}"
      - name: step 2
        run: |
          echo "This is step 2 of job dev"

  job-preprod:
    runs-on: ubuntu-latest
    needs: job-dev
    environment: pre-prod
    steps:
      - name: Job 2
        run: echo "This is job-preprod, which depends on job-dev"
  
  job-prod:
    runs-on: ubuntu-latest
    needs: [job-preprod]
    environment: prod
    steps:
      - name: Job 3
        run: echo "This is job-prod, which depends on job-preprod"